# Generated by Django 4.2.4 on 2023-08-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.TextField(default='default description'),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default='Default description'),
        ),
    ]
