# Generated by Django 4.2.4 on 2023-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.TextField(default='GSeries Production'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(default='GSeries Production'),
        ),
    ]
