# Generated by Django 4.2.4 on 2023-08-25 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('package', models.CharField(choices=[('bronze', 'Bronze Package'), ('platinum', 'Platinum Package'), ('royal', 'Royal Package')], max_length=20)),
                ('additional_comments', models.TextField(blank=True)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
