# Generated by Django 4.2.4 on 2023-08-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('role', models.CharField(max_length=100)),
                ('twitterlink', models.URLField(blank=True)),
                ('facebooklink', models.URLField(blank=True)),
                ('tiktoklink', models.URLField(blank=True)),
                ('instagramlink', models.URLField(blank=True)),
            ],
        ),
    ]
