# Generated by Django 4.2.4 on 2023-09-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.CharField(default='type...', max_length=100),
        ),
    ]
